name: machineMonitor_CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest    # or windows-latest, macos-latest…

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: sync requirements
        run: python __init__.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests with pytest
        run: pytest api/test.py -rx    # failure only -> -rA = (all)